'use client';

import Header from '@/components/Header';
import Head from 'next/head';
import Container from 'react-bootstrap/Container';
import Button from 'react-bootstrap/Button';
import { GetServerSidePropsContext } from 'next';
import { createClient as createClientServer } from '@/lib/supabase/server';
import { createClient as createClientClient } from '@/lib/supabase/client';
import { Post } from '@/types/Post';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import PostEditForm from '@/components/PostEditForm';
import usePosts from '@/hooks/usePosts';
import { useRouter } from 'next/router';
import { Session } from '@supabase/supabase-js';

type Props = {
  post: Post;
};

const PostPage = ({ post }: Props) => {
  const router = useRouter();
  const [isEditing, setIsEditing] = useState(false);
  const { updatePost } = usePosts();

  // ✅ replaces seUser()
  const [session, setSession] = useState<Session | null>(null);

  useEffect(() => {
    const supabase = createClientClient();
    supabase.auth.getSession().then(({ data: { session } }) => {
      setSession(session);
    });

    const { data: listener } = supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session);
    });

    return () => {
      listener.subscription.unsubscribe();
    };
  }, []);

  const user = session?.user;

  const handleSubmit = async (title: string, body: string) => {
    await updatePost(post.id, title, body);
    router.reload();
  };

  return (
    <>
      <Head>
        <title>Posts list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Container>
          <Link href="/" legacyBehavior>
            <Button variant="link">{'<'}Back to all posts</Button>
          </Link>
          {isEditing ? (
            <PostEditForm post={post} saveForm={handleSubmit} />
          ) : (
            <>
              <h1>{post.title}</h1>
              <div>{post.body}</div>
              {user && user.id === post.author && (
                <Button onClick={() => setIsEditing(true)}>Edit post</Button>
              )}
            </>
          )}
        </Container>
      </main>
    </>
  );
};

export default PostPage;

export async function getServerSideProps(context: GetServerSidePropsContext) {
  const supabase = await createClientServer();

  const { data: post, error } = await supabase
    .from('posts')
    .select('*')
    .eq('id', context.params?.id)
    .single();

  if (error) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      post,
    },
  };
}
