import Header from '@/components/Header';
import Head from 'next/head';
import usePosts from '@/hooks/usePosts';
import { useRouter } from 'next/router';
import PostEditForm from '@/components/PostEditForm';
import { useState } from 'react';
import Link from 'next/link';

const NewPostPage = () => {
  const router = useRouter();
  const { createPost } = usePosts();
  const [alertMessage, setAlertMessage] = useState<{
    type: string;
    message: string;
  } | null>(null);

  const handleSubmit = async (title: string, body: string) => {
    try {
      const { id } = await createPost(title, body);
      router.push(`/posts/${id}`);
    } catch (error: any) {
      setAlertMessage({ type: 'danger', message: error.message });
    }
  };

  return (
    <>
      <Head>
        <title>Posts list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <Link href="/">
            <button>{'<'}Back to all posts</button>
          </Link>

          {alertMessage && (
            <span className={`alert alert-${alertMessage.type}`}>
              {alertMessage.message}
            </span>
          )}
          <h1>New Post</h1>
          <PostEditForm saveForm={handleSubmit} />
        </div>
      </main>
    </>
  );
};

export default NewPostPage;